### PR TITLE
updated the code values

### LINKED ISSUE #1: 🐞 Fix game
The game is broken ⚡  because it is too slow. Go to [docs/index.html](../blob/main/docs/index.html#L78) line 78 and adjust  and  properties of speed and set the to the following values:

speed   = { start: 0.6, decrement: 0.005, min: 0.1 }

### PR DESCRIPTION
**Pull request by jsmorgan**
Values were changed in the docs/index.html

### CODE REVIEW

**Review by mwijerrodtracy — CHANGES_REQUESTED** [review]
Do you really think this change will work? It's a crap change. I think you should rebuilt it all to be a slider for changing speed.

**Comment by mwijerrodtracy** [comment]
Perfect, this is the change I was looking for

**Comment by CarterBland** [comment]
> Do you really think this change will work? It's a crap change. I think you should rebuilt it all to be a slider for changing speed.

yeah this change is crappy 👎

**Comment by jsmorgan** [comment]
image

**Pull request merged**
